# Generated by Django 3.2.13 on 2022-06-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
