# Generated by Django 3.2.13 on 2022-06-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0002_auto_20220619_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
