# Generated by Django 3.2.13 on 2022-06-19 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0003_auto_20220619_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryType_id',
            new_name='categoryType',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categoryType_id',
            new_name='categoryType',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
