# Generated by Django 3.2.13 on 2022-06-19 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0004_auto_20220619_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoryType',
        ),
    ]
