# Generated by Django 3.2.13 on 2022-06-19 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0006_alter_product_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryType',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myrestaurant.table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Admin', max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryType',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
