# Generated by Django 3.2.13 on 2022-06-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0007_auto_20220619_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
