# Generated by Django 3.2.13 on 2022-06-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0010_alter_category_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('image_path', models.ImageField(upload_to='myrestaurant/static/images/')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrestaurant.category')),
            ],
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrestaurant.victual'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
