# Generated by Django 3.2.13 on 2022-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0011_auto_20220621_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victual',
            name='image_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
