# Generated by Django 3.2.13 on 2022-06-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0012_alter_victual_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_path',
            field=models.FileField(null=True, upload_to='myrestaurant/static/images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='victual',
            name='image_path',
            field=models.FileField(upload_to='images/'),
        ),
    ]
