# Generated by Django 3.2.13 on 2022-06-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0013_auto_20220622_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_path',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
