# Generated by Django 3.2.13 on 2022-06-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0015_auto_20220622_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_path',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='victual',
            name='image_path',
            field=models.FileField(upload_to=''),
        ),
    ]
