# Generated by Django 3.2.13 on 2022-06-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0017_alter_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
