# Generated by Django 3.2.13 on 2022-06-25 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0018_alter_table_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('victual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrestaurant.victual')),
            ],
        ),
    ]
