# Generated by Django 3.2.13 on 2022-06-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0019_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='Coke', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
