# Generated by Django 3.2.13 on 2022-06-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0020_auto_20220625_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_path',
            field=models.FileField(default='fdjfjdfhdskfhsf', upload_to=''),
            preserve_default=False,
        ),
    ]
