# Generated by Django 3.2.13 on 2022-06-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0024_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
