# Generated by Django 3.2.13 on 2022-06-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0025_auto_20220628_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='myrestaurant.user'),
            preserve_default=False,
        ),
    ]
