# Generated by Django 3.2.13 on 2022-06-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0026_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='category',
        ),
    ]
