# Generated by Django 3.2.13 on 2022-06-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0027_remove_orderdetail_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='victual',
        ),
    ]
