# Generated by Django 3.2.13 on 2022-06-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0028_rename_product_orderdetail_victual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='amount',
            new_name='price',
        ),
    ]
