# Generated by Django 3.2.13 on 2022-07-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0029_rename_amount_orderdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victual',
            name='image_path',
            field=models.FileField(default='media/no_image.jpg', null=True, upload_to=''),
        ),
    ]
