# Generated by Django 3.2.13 on 2022-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0030_alter_victual_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victual',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
