# Generated by Django 3.2.13 on 2022-07-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0032_alter_victual_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victual',
            name='image_path',
            field=models.ImageField(default='media/no_image.jpg', null=True, upload_to=''),
        ),
    ]
